config/routes.rb
PersonalWebsite::Application.routes.draw do
  root 'pages#home'
  match 'about',    to: 'pages#about',    via: 'get'
  match 'work',   to: 'pages#work',   via: 'get'
  match 'projects', to: 'pages#projects', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def work
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>colin m leung</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="index, follow, noarchive"/>
  <meta name="googlebot" content="noarchive"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body data-spy="scroll" data-target="#sidebarnav" data-offset="100">
  <div class="wrapper">
    <header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <%= link_to 'colin m leung', root_path, class: "navbar-brand", style: "color: white;" %>
        </div>
        <nav class="pull-right">
          <ul class="nav navbar-nav">
            <li <%= if current_page?(:controller => 'pages', :action => 'about')
                      "class=active"
                    end %>><%= link_to 'About', about_path %></li>
            <li <%= if current_page?(:controller => 'pages', :action => 'work')
                      "class=active"
                    end %>><%= link_to 'Work', work_path %></li>
            <li <%= if current_page?(:controller => 'pages', :action => 'projects')
                      "class=active"
                    end %>><%= link_to 'Projects', projects_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <div class="push"></div>
  </div>
  <div class="footer">
    <div class="container">
      <%= link_to image_tag("social-011_linkedin.png", alt: "linkedin", style: "float: right; padding-top: 5px; padding-left: 25px;"), "http://www.linkedin.com/pub/colin-leung/46/310/b83", :target => "_blank" %>
      <%= link_to image_tag("github-9-xxl.png", alt: "github", size: "60x60", style: "float: right; padding-left: 25px;"), "https://github.com/colinmleung", :target => "_blank" %>
      <%= link_to image_tag("1379827905_aiga_mail_inver.png", size: "25x25", alt: "email", style: "float: right; padding-top: 5px;"), "mailto:colinmleung@gmail.com", :target => "_blank" %>
      <span style="font-size: 10px; float: right; padding-right: 50px; padding-top: 17px;">Copyright © 2014 Colin Leung. All Rights Reserved.</span>
    </div>
  </div>
</body>

</html>

app/views/pages/about.html.erb
<div id="content" role="main" style="padding-top: 75px;">
  <div class="container">
    <p>Hi, I'm Colin. I'm a recent Engineering Physics graduate who's currently developing web applications for PNI Digital Media.</p>

    <p>Previously, I worked as a web developer at Ingenium Technologies doing full-stack feature development for an enterprise lead management application. Other work experiences I've had include researching cement image analysis algorithms in Japan, measuring power consumption on smartphones running Angry Birds, and designing interfaces for demonstrating ship detection algorithms.</p>

    <p>I've built a whole slew of applications to learn new technologies and develop my technical skills. My latest application involves combining multiple geographically-focused real-time data sources (such as Twitter) and processing the data (using clustering, sentiment analysis, etc.) such that users can engage with the data and discover interesting relationships themselves.</p>

    <p>I'm currently looking for full-time opportunities in software development. My greatest strengths lie in my generalist technical background and my "get 'er done" attitude; if you need someone who has previous development experience, learns quickly, and can get things done, send me an email at <%= mail_to "colinmleung@gmail.com" %>.</p>

    <p>Thanks for visiting!</p>
  </div>
</div>

app/views/pages/home.html.erb
<div id="content" class="centered">
  <div class="container">
    <%= image_tag("IMG_20130924_123240_smaller.jpg", id: "home_pic", size: "200x150", alt: "Picture of me", style: "float: left; margin-top: 23px; border-style: solid; border-width: 3px;") %>
    <div class="offcenter">
      <h1>Hi, I'm a web developer who likes learning new technologies and prototyping cool things.</h1>
      <br/>
      <a class="btn btn-lg btn-primary" href="colinmleung_resume.pdf" target="_blank">View Resume</a>
    </div>
  </div>
</div>

app/views/pages/projects.html.erb
<div class="container">
  <div class="row">
    <div id="sidebarnav" style="width: 250px;" data-spy="affix">
      <ul id="local-nav-list" class="nav nav-pills nav-stacked nav-list">
        <li><a href="#weather">Real-Time Tweet Sentiment Vs. Weather Application</a></li>
        <li><a href="#cloud">Hashtag Word Cloud</a></li>
        <li><a href="#sentiment">Reddit Sentiment Analysis Application</a></li>
        <li><a href="#text">Text Adventure Game</a></li>
        <li><a href="#work">Work Journal Web Application</a></li>
        <li><a href="#localization">Localization System for Telehealth Applications</a></li>
        <li><a href="#racing">Autonomous Racing Robot</a></li>
      </ul>
    </div>
    <div style="margin-left: 270px; margin-top: -20px; width: 50%;">
      <div>
        <h2><span id="weather"> &nbsp; </span>Real-Time Tweet Sentiment Vs. Weather Application</h2>
        <%= image_tag("479 Proposal Architecture.png", size: "600x800", alt: "Sentiment Vs. Weather Architecture", style: "padding-left: 0px;") %>
        <br/><br/>
        <p>I built my capstone project in collaboration with two team members, <%= link_to("Chris", "http://www.chrisjyyoon.com", target: "_blank") %> and <%= link_to("Richard", "http://www.richardxlee.com", target: "_blank") %>, with the guidance of the UBC MAGIC Lab. The purpose of the project is to find and display interesting correlations in data using a web application, and engage the citizens of Vancouver. We chose to analyze how the weather affected Tweet sentiment. To accomplish this task, we used Java to perform data clustering, and Javascript to create visually engaging displays. My personal contribution was to build the dynamic Javascript front-end, incorporating Google Maps and graphs using the d3.js data visualization library. I also managed the data import process for the application.</p>
        <br/>
        <%= link_to("Code", "https://github.com/ubc-magic-students/enph479-2013", target: "_blank") %><br/>
        <%= link_to("Final report", "http://docs.google.com/document/d/1aiWd8UfBQMTlDHTI4iOwzUg1m3aDJ7nWPc6TxvaylVQ/edit", target: "_blank") %>
      </div>
      <div>
        <h2><span id="cloud"> &nbsp; </span>Hashtag Word Cloud</h2>
        <p>I built a visual web experiment during the summmer, after being inspired by <%= link_to("Twistori", "http://www.twistori.com", :target => "_blank")%>. I also used this project as an opportunity try out Node.js and MongoDB.</p>
        <%= image_tag("Tweet Word Cloud.png", size: "450x600", alt: "Hashtag Word Cloud", style: "padding-left: 100px;") %>
        <p>The web application itself is built using the Express framework, and it also runs a Twitter stream data importing/exporting process in parallel. Some technical issues I had to solve included:</p>
        <ul style="list-style: none;">
          <li>How do I get data from the back-end to the front-end in real-time?  Socket.IO</li>

          <li>How do I get streaming data from Twitter?       Twit library</li>

          <li>How can I turn a list of hashtags into a list of hashtag frequencies? MapReduce.</li>

          <li>How do I get database entries to automatically expire?      The time-to-live attribute.</li>
        </ul>
        <%= link_to("Code", "https://github.com/colinmleung/tweet-word-cloud", target: "_blank") %>
      </div>
      <div>
        <h2><span id="sentiment"> &nbsp; </span>Reddit Sentiment Analysis Application</h2>
          <p>A web application that allows users to enter a search term and analyze the first nine
                        reddit post results for their sentiment polarity</p>
          <figure>
            <%= image_tag("rsa_pic_processed.png", size: "800x500", alt: "Reddit Sentiment Analysis Application Screenshot") %>
          </figure>
          <br/>
          <%= link_to("Code", "https://github.com/colinmleung/reddit-sentiment-analysis", target: "_blank") %>
      </div>
      <div>
        <h2><span id="text"> &nbsp; </span>Text Adventure Game</h2>
          <p>A console text adventure game</p>
          <figure>
            <%= image_tag("dungeon_crawler.png", size: "750x300", alt: "Text Adventure Game Screenshot") %>
          </figure>
          <br/>
          <%= link_to("Code", "https:/
          /github.com/colinmleung/dungeon-crawler", target: "_blank") %>
      </div>
      <div>
        <h2><span id="work"> &nbsp; </span>Work Journal Web Application</h2>
          <p>A CRUD web application that allows users to create templates of journal prompts and
                        use them to write journal entries</p>
          <figure>
            <%= image_tag("workjournal.png", size: "425x350", alt: "Templates Page Screenshot") %>
          </figure>
          <br/>
          <%= link_to("Code", "https://github.com/colinmleung/work-journal", target: "_blank") %>
      </div>
      <div>
        <h2><span id="localization"> &nbsp; </span>Localization System for Telehealth Applications</h2>
          <p>A local positioning system which uses a combination of ultrasound and radio frequency waves to accurately locate moving objects</p>
          <figure>
            <%= image_tag("localization.png", size: "440x325", alt: "System overview of the localization device") %>
            <!--<figcaption>Interactions within our localization system to locate moving objects.</figcaption>-->
          </figure>
          <br/>
          <%= link_to("Draft of final report", "https://docs.google.com/document/d/1RKTXfA3HNPnZP0qF2K-x9H2uwWuRlz_UBX85jUnbOVM/edit", target: "_blank") %>
      </div>
      <div>
        <h2><span id="racing"> &nbsp; </span>Autonomous Racing Robot</h2>
          <p>A tape-following robot with control algorithms based on a primitive finite
                        state machine</p>
          <figure>
            <%= image_tag("robot.jpg", size: "304x228", alt: "The Party Van is ON FIRE!") %>
            <!--<figcaption>Profile view of our winning robot, The Party Van.</figcaption>-->
          </figure>
          <br/>
          <%= link_to("Video of the final race", "http://www.youtube.com/watch?v=ouQ41usUmjI", target: "_blank") %><br/>
          <%= link_to("Robot's Website", "http://phys253-partyvan-2010.net84.net/", target: "_blank") %>
      </div>
    </div>
  </div>
</div>

app/views/pages/resume.html.erb
<% content_for :head do %>
  <%=stylesheet_link_tag "styleresume" %>
<% end %>

<%= render 'header' %>
<%= render 'navigation' %>
<div id="bodycontent">
  <div id="resume">
    <object data='resume.pdf#'
                type='application/pdf'
                width='750'
                height='1035'>
      <p>It appears your Web browser is not configured to display PDF files.
                No worries, just <a href='resume.pdf'>click here to download the PDF file.</a></p>
    </object>
  </div>
</div>

app/views/pages/work.html.erb
<div class="container">
  <div class="row">
    <div id="sidebarnav" style="width: 250px;" data-spy="affix">
      <ul id="local-nav-list" class="nav nav-pills nav-stacked nav-list">
        <li><a href="#web">Full-Stack Web Developer</a></li>
        <li><a href="#power">Power Measurement Engineer</a></li>
        <li><a href="#image">Image Analysis Algorithm Developer</a></li>
        <li><a href="#interface">Interface Developer</a></li>
      </ul>
    </div>
    <div style="margin-left: 270px; margin-top: -20px; width: 50%;">
      <div>
        <h2><span id="web"> &nbsp; </span>Full Stack Web Developer</h2>
        <p style="padding-left:35px;">@ <%= link_to "PNI Digital Media", "http://www.pnimedia.com/", :target => "_blank" %>, June 2014 - Current</p>
          <p>I currently work as a developer in the Engineering team, delivering medium-term, high-value projects to our retail clients. We build our products on the ASP.NET platform using C#, as well as the typical front-end languages.</p>
          <p style="padding-left:35px;">@ <%= link_to "Ingenium Technologies", "http://www.constructionpoints.com/", :target => "_blank" %>, January 2013 - August 2013 (8 months)</p>
          <p>I was responsible for developing new features for our construction lead management application. I programmed with HTML, CSS (LESS), and Javascript (jQuery) on the front-end, and developed the backend with C# using the ASP.NET MVC framework. I worked within a small development team that used Agile practices such as holding stand-up meetings and creating user stories.</p>

          <p>Some tasks I took on include:</p>

          <ul>
            <li>building mobile-friendly views</li>
            <li>adding Javascript widgets</li>
            <li>building out an administration panel for customer support</li>
            <li>refactoring the front-end to transform specialized code into a more componentized form</li>
            <li>creating automated tests in Selenium</li>
            <li>adding Google Analytics events to better understand application usage</li>
          </ul>
      </div>
      <div>
        <h2><span id="power"> &nbsp; </span>Power Measurement Engineer</h2>
        <p style="padding-left:35px;">@ <%= link_to "Broadcom", "http://www.broadcom.com/", :target => "_blank" %>, May 2012 - December 2012 (8 months)</p>
          <p>I worked as a developer supporting the Power Management Team for 8 months from May to December 2012. I was responsible for measuring the power consumption of system-on-chip devices as the firmware evolved, and as new chipsets came out.</p>

          <p>In order to create reproducible results, I wrote low-level driver scripts to replicate user behaviour (such as playing Angry Birds). It was also necessary to create physical test harnesses to accurately measure power consumption during use-cases such as video recording.</p>

          <p>Being the most familiar with the measurement setups, I debugged power regressions as new software came out. Debugging some of these issues would prove incredibly complex, requiring measurements taken in multiple hardware configurations to find the root cause of the issue. In situations like these, documentation on the wiki, on JIRA, and engineering logbooks proved vital to solving issues.</p>
      </div>
      <div>
        <h2><span id="image"> &nbsp; </span>Image Analysis Algorithm Developer</h2>
          <p style="padding-left:35px;">@ <%= link_to "Taiheiyo Cement", "http://www.taiheiyo-cement.co.jp/english/", :target => "_blank" %>, May 2011 - December 2011 (8 months)</p>
          <p>At Taiheiyo, my role was to provide programming expertise for the Cement Chemistry team, helping them to quantify their cement samples using image analysis algorithms.<p>

          <p>In the first few months, I assessed my coworkers needs, and built prototype scripts in Scilab. The team decided they would like to examine multiple types of cement in various ways, and I decided that building an image analysis toolkit would be best. I then architected an application using Windows Presentation Foundation for the interface, and OpenCV as the processing backend.</p>

          <p>After reading cement analysis research papers, it became obvious I would have to invent the analysis algorithms myself. At that point, programming the entire analysis framework myself would take too long, and I decided that coming up with algorithms using off-the-shelf analysis solutions would deliver the best results for the team.</p>

          <p>After more research, which included preparing my own cement samples and taking pictures with electron microscopes, I was able to use a sequence of ImageJ operations to come up with two successful algorithms.</p>

          <a href="DEC13_Quantifying Cement Systems using Image Analysis.pptx" target="_blank">Quantifying Cement Samples using Image Analysis</a> (with permission of Taiheiyo Cement Corporation)
      </div>
      <div>
        <h2><span id="interface"> &nbsp; </span>Interface Developer</h2>
          <p style="padding-left:35px;">@ <%= link_to "A.U.G. Signals", "http://www.augsignals.com", :target => "_blank" %>, January 2010 - April 2010 (4 months)</p>
          <p>My role was to work closely with image analysis researchers and create interfaces to expose the power of their algorithms to clients. These interfaces would be completed on a per-project basis, using whatever technology suited the project at hand. I created interfaces in MATLAB and C using the MFC framework. In addition to this role, I wrote bash scripts and  set up development environments and libraries such as <%= link_to "Gazebo", "http://gazebosim.org", :target => "_blank" %>.</p>
          <p>I investigated how to improve interfaces using techniques such as implementing loading bars and changing the interface size to accomodate different file type resolutions. Due to the large number of client change requests and rapid algorithmic development, I also learnt about the importance of refactoring applications to be maintainable.</p>
      </div>
    </div>
  </div>
</div>